<?php define('STR_DIR_DEFAULTH','http://localhost/admin/');
define('STR_DIR_FRAMEWORK_DEFAULTH',STR_DIR_DEFAULTH.'includes/');
define('STR_DIR_IMAGE_DEFAULTH',STR_DIR_DEFAULTH.'includes/image/');
define('STR_DIR_CLASSES_DEFAULTH',STR_DIR_DEFAULTH.'includes/classes/');
define('STR_DIR_CSS_DEFAULTH',STR_DIR_DEFAULTH.'includes/css/');
define('STR_DIR_ERROR_DEFAULTH',STR_DIR_DEFAULTH.'includes/error/');
define('STR_DIR_JS_DEFAULTH',STR_DIR_DEFAULTH.'includes/js/');
define('STR_DIR_LANGUAGE_DEFAULTH',STR_DIR_DEFAULTH.'includes/language/');
define('STR_DIR_CONTROLLER_DEFAULTH',STR_DIR_DEFAULTH.'index.php/');
define('STR_DIR_VIEW_DEFAULTH',STR_DIR_DEFAULTH.'Vistas/');
define('STR_DIR_MODEL_DEFAULTH',STR_DIR_DEFAULTH.'Modelos/');
define('STR_DIR_AUTO_COMPLETE_DEFAULTH',STR_DIR_DEFAULTH.'includes/autocompletes/');
define('STR_DIR_AJAX_SEARCH_DEFAULTH',STR_DIR_DEFAULTH.'Controladores/ajax/');
define('STR_DIR_DOWNLOAD_DEFAULTH',STR_DIR_DEFAULTH.'download/');
define('STR_DIR_REPO_DEFAULTH',STR_DIR_DEFAULTH.'Vistas/repositorio/');
define('STR_DIR_REPO_AJAX_DEFAULTH',STR_DIR_DEFAULTH.'includes/autocompletes/');
